import { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import OrganizerShell, { Icon } from '../components/OrganizerShell'

const statuses = { 1:'holiday',2:'present',3:'present',4:'present',5:'present',6:'leave',7:'holiday',8:'holiday',9:'present',10:'present',11:'present',12:'present',13:'late',14:'holiday',15:'holiday',16:'present',17:'present',18:'present',19:'present',20:'present',21:'holiday',22:'holiday',23:'present',24:'leave' }
const dots = { present:'bg-emerald-500', late:'bg-amber-500', leave:'bg-blue-500', absent:'bg-rose-500', holiday:'bg-slate-300' }
const summary = [['Present','14','bg-emerald-500'],['Late','1','bg-amber-500'],['On Leave','2','bg-blue-500'],['Absent','0','bg-rose-500']]
const cardClass = 'rounded-[30px] border border-amber-200 bg-white shadow-[0_22px_70px_rgba(212,175,55,0.12)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_32px_95px_rgba(212,175,55,0.22)]'

function Calendar({ selected, onSelect }) {
  const days = useMemo(() => Array.from({length:28},(_,i)=>i+1),[])
  return <section className={cardClass}><div className="flex flex-col gap-4 border-b border-amber-100 px-6 py-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-amber-100 text-amber-600"><Icon name="calendar" /></div><h2 className="text-2xl font-semibold">February 2026</h2></div><div className="flex w-full max-w-xs justify-between rounded-xl bg-[#FFF8E6] px-5 py-3"><button>&lsaquo;</button><button>&rsaquo;</button></div></div><div className="p-6 sm:p-8"><div className="grid grid-cols-7 gap-2 text-center text-xs font-semibold uppercase tracking-[.16em] text-[#6B5C3B]">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><span key={day}>{day}</span>)}</div><div className="mt-7 grid grid-cols-7 gap-2">{days.map(day=><button key={day} onClick={()=>onSelect(day)} className={`flex aspect-square min-h-16 flex-col items-center justify-center rounded-2xl border text-sm font-semibold transition ${selected===day?'border-amber-400 bg-[#FFF8E6] shadow-[0_14px_40px_rgba(245,158,11,.16)]':'border-transparent hover:border-amber-200 hover:bg-white'}`}><span>{day}</span><span className={`mt-2 h-2.5 w-2.5 rounded-full ${dots[statuses[day]]}`} /></button>)}</div><div className="mt-8 flex flex-wrap justify-center gap-5 border-t border-amber-100 pt-6 text-sm text-[#6B5C3B]">{[['Present','present'],['Late','late'],['Leave','leave'],['Absent','absent'],['Holiday','holiday']].map(([label,status])=><span key={label} className="inline-flex items-center gap-2"><span className={`h-3 w-3 rounded-full ${dots[status]}`} />{label}</span>)}</div></div></section>
}

function Insight({ day }) {
  const status = statuses[day]
  const label = {present:'Present',late:'Late Arrival',leave:'Approved Leave',holiday:'Holiday'}[status]
  return <aside className={`${cardClass} p-7`}><p className="text-sm font-semibold uppercase tracking-[.26em] text-[#9A8553]">Daily Insight</p>{day?<div className="mt-9"><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-[#FFF8E6] text-amber-600"><Icon name="calendar" className="h-9 w-9" /></div><h2 className="mt-7 text-3xl font-semibold">Feb {day}, 2026</h2><p className="mt-3 text-lg font-semibold text-amber-700">{label}</p><div className="mt-7 space-y-4"><div className="rounded-2xl border border-amber-100 bg-[#FFFDF7] p-4"><p className="font-semibold">Check In</p><p className="mt-1 text-sm text-[#6B5C3B]">{status==='present'?'09:06 AM':status==='late'?'09:38 AM':'--'}</p></div><div className="rounded-2xl border border-amber-100 bg-[#FFFDF7] p-4"><p className="font-semibold">Verification</p><p className="mt-1 text-sm text-[#6B5C3B]">Face ID and head office geofence</p></div></div></div>:<div className="flex min-h-[480px] flex-col items-center justify-center text-center"><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-[#FFF8E6] text-amber-600"><Icon name="calendar" className="h-9 w-9" /></div><h2 className="mt-7 text-2xl font-semibold">No Date Selected</h2><p className="mt-3 max-w-xs text-sm leading-7 text-[#6B5C3B]">Select a date to review your organizer attendance record.</p></div>}</aside>
}

export default function OrganizerAttendance() {
  const [selected,setSelected]=useState(null)
  return <OrganizerShell title="My Attendance" variant="attendance"><main className="relative mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:py-12"><section className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.28em] text-[#9A8553]">Personal Records</p><h2 className="mt-3 text-4xl font-semibold sm:text-5xl">Attendance Calendar</h2><p className="mt-3 text-base text-[#6B5C3B] sm:text-lg">Review your monthly Organizer attendance.</p></div><button className="inline-flex h-11 items-center gap-2 rounded-xl border border-amber-200 bg-white px-4 text-sm font-semibold hover:bg-[#FFF8E6]"><Icon name="download" className="h-4 w-4" />Download Report</button></section><section className="mt-8 grid gap-5 lg:grid-cols-4">{summary.map(([label,value,color],index)=><motion.article key={label} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:index*.06}} className={`${cardClass} p-6`}><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-[#6B5C3B]">{label}</p><p className="mt-5 text-4xl font-semibold">{value}</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#FFF8E6]"><span className={`h-3 w-3 rounded-full ${color}`} /></span></div></motion.article>)}</section><section className="mt-8 grid gap-6 xl:grid-cols-[1fr_.48fr]"><Calendar selected={selected} onSelect={setSelected} /><Insight day={selected} /></section></main></OrganizerShell>
}
