import { useState } from 'react'
import { motion } from 'framer-motion'
import OrganizerShell, { Icon } from '../components/OrganizerShell'

const metrics = [
  { label: 'Total Employees', value: '156', note: '+12% from last month', icon: 'users' },
  { label: 'Active Managers', value: '18', note: 'Across 6 departments', icon: 'userCheck' },
  { label: 'Present Today', value: '142', note: '91% attendance', icon: 'trend' },
  { label: 'Pending Requests', value: '23', note: 'Requires attention', icon: 'clock' }
]

const departments = [
  { name: 'Engineering', staff: 45, attendance: 94 }, { name: 'Sales', staff: 32, attendance: 88 },
  { name: 'Marketing', staff: 28, attendance: 91 }, { name: 'Operations', staff: 25, attendance: 89 },
  { name: 'HR', staff: 15, attendance: 95 }, { name: 'Finance', staff: 11, attendance: 92 }
]

const alerts = [
  { name: 'John Smith', detail: 'Absent for 3 consecutive days', level: 'High' },
  { name: 'Mary Johnson', detail: 'Late arrival pattern this month', level: 'Medium' },
  { name: 'David Lee', detail: 'Leave balance below threshold', level: 'Low' }
]

const performers = [['Emily Davis', 'Engineering', '100%'], ['Rachel Green', 'Sales', '98%'], ['Michael Chen', 'Engineering', '97%'], ['Sarah Johnson', 'Marketing', '96%']]

const cardClass = 'rounded-[30px] border border-amber-200 bg-white shadow-[0_22px_70px_rgba(212,175,55,0.12)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_32px_95px_rgba(212,175,55,0.22)]'

function Tracker() {
  const [clockedIn, setClockedIn] = useState(false)
  return <section className={`${cardClass} p-6`}><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-amber-100 text-amber-600"><Icon name="clock" className="h-7 w-7" /></div><div><h2 className="text-2xl font-semibold">My Attendance</h2><p className="mt-1 text-sm text-[#6B5C3B]">Organizer work session</p></div></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-amber-100 bg-[#FFFDF7] p-4"><p className="text-xs font-semibold text-[#6B5C3B]">Check In</p><p className="mt-3 text-xl font-semibold">{clockedIn ? '09:08' : '--:--'}</p></div><div className="rounded-2xl border border-amber-100 bg-[#FFFDF7] p-4"><p className="text-xs font-semibold text-[#6B5C3B]">Check Out</p><p className="mt-3 text-xl font-semibold">--:--</p></div></div><div className="mt-4 flex items-center gap-3 rounded-2xl border border-amber-100 bg-white p-4"><Icon name="location" className="text-amber-600" /><div><p className="text-sm font-semibold">{clockedIn ? 'Location Verified' : 'Location Pending'}</p><p className="mt-1 text-xs text-[#6B5C3B]">{clockedIn ? 'Head office perimeter confirmed' : 'Clock in to detect location'}</p></div></div><div className="mx-auto mt-6 flex h-40 w-40 flex-col items-center justify-center rounded-full border border-amber-100 bg-white shadow-[0_20px_65px_rgba(13,12,29,0.12)] ring-8 ring-[#FFF8E6]"><p className="text-2xl font-semibold tracking-[0.08em]">{clockedIn ? '01:16:42' : '00:00:00'}</p><p className="mt-3 text-xs uppercase tracking-[0.22em] text-[#6B5C3B]">Duration</p></div><button onClick={() => setClockedIn(current => !current)} className="mt-6 h-12 w-full rounded-xl bg-gradient-to-r from-amber-400 to-amber-600 text-sm font-semibold text-white shadow-[0_18px_55px_rgba(245,158,11,0.22)]">{clockedIn ? 'Clock Out' : 'Clock In Now'}</button></section>
}

export default function OrganizerDashboard() {
  return <OrganizerShell title="Dashboard"><main className="relative mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:py-12"><section className="relative overflow-hidden rounded-[34px] border border-white/75 bg-white/80 p-7 shadow-[0_28px_90px_rgba(212,175,55,0.14)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_34px_105px_rgba(212,175,55,0.2)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_92%_20%,rgba(245,158,11,0.18),transparent_30%),linear-gradient(135deg,rgba(255,255,255,0.92),rgba(255,248,230,0.7))]" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.28em] text-[#9A8553]">Organization Overview</p><h2 className="mt-3 text-4xl font-semibold sm:text-5xl">Good morning, <span className="text-amber-600">Organizer</span></h2><p className="mt-3 text-base text-[#6B5C3B] sm:text-lg">Organization-wide attendance and performance overview.</p></div><button className="inline-flex h-11 items-center gap-2 rounded-xl border border-amber-200 bg-white px-4 text-sm font-semibold hover:bg-[#FFF8E6]"><Icon name="download" className="h-4 w-4" />Download Report</button></div></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-4">{metrics.map((item,index) => <motion.article key={item.label} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:index*.06}} className={`${cardClass} p-6`}><div className="flex items-start justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#FFF8E6] text-amber-600"><Icon name={item.icon} /></div><span className="text-amber-600">↗</span></div><p className="mt-7 text-sm font-semibold text-[#6B5C3B]">{item.label}</p><p className="mt-3 text-4xl font-semibold">{item.value}</p><p className="mt-2 text-sm text-[#6B5C3B]">{item.note}</p></motion.article>)}</section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[1fr_.42fr]"><div className="space-y-6"><section className={`${cardClass} p-6`}><div className="flex items-start justify-between"><div><h2 className="text-2xl font-semibold">Attendance Trends</h2><p className="mt-1 text-sm text-[#6B5C3B]">Weekly organization presence</p></div><span className="rounded-full bg-[#FFF8E6] px-3 py-1 text-xs font-semibold">This Week</span></div><svg viewBox="0 0 700 260" className="mt-7 w-full" aria-label="Attendance trend chart"><defs><linearGradient id="organizerChart" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#F59E0B" stopOpacity=".34" /><stop offset="1" stopColor="#F59E0B" stopOpacity=".03" /></linearGradient></defs><path d="M30 180 C140 155 210 170 300 130 S470 145 550 95 S640 115 680 82 L680 230 L30 230Z" fill="url(#organizerChart)" /><path d="M30 180 C140 155 210 170 300 130 S470 145 550 95 S640 115 680 82" fill="none" stroke="#F59E0B" strokeWidth="5" strokeLinecap="round" /><path d="M30 218 C150 225 220 210 310 220 S470 205 560 216 S640 205 680 210" fill="none" stroke="#E11D48" strokeWidth="3" /><path d="M30 230h650" stroke="#E8D9A8" /></svg></section><section className={`${cardClass} p-6`}><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">Recent Alerts</h2><button className="text-sm font-semibold text-amber-700">View All</button></div><div className="mt-5 space-y-3">{alerts.map(alert => <div key={alert.name} className="flex items-center justify-between gap-4 rounded-2xl border border-amber-100 bg-[#FFFDF7] p-4 transition hover:-translate-y-1 hover:bg-white hover:shadow-sm"><div><p className="font-semibold">{alert.name}</p><p className="mt-1 text-sm text-[#6B5C3B]">{alert.detail}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${alert.level === 'High' ? 'bg-rose-100 text-rose-700' : alert.level === 'Medium' ? 'bg-amber-100 text-amber-700' : 'bg-blue-100 text-blue-700'}`}>{alert.level}</span></div>)}</div></section></div><Tracker /></section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[1fr_.42fr]"><div><h2 className="text-2xl font-semibold">Department Performance</h2><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{departments.map(dept => <article key={dept.name} className={`${cardClass} p-5`}><div className="flex items-center justify-between"><h3 className="text-lg font-semibold">{dept.name}</h3><span className="text-sm font-semibold text-amber-700">{dept.attendance}%</span></div><p className="mt-5 text-3xl font-semibold">{dept.staff}<span className="ml-2 text-xs font-normal text-[#6B5C3B]">staff</span></p><div className="mt-5 h-2 overflow-hidden rounded-full bg-amber-100"><div className="h-full rounded-full bg-gradient-to-r from-amber-400 to-amber-600" style={{width:`${dept.attendance}%`}} /></div></article>)}</div></div><section className={`${cardClass} h-fit p-6`}><h2 className="text-2xl font-semibold">Top Performers</h2><div className="mt-6 space-y-5">{performers.map(([name,dept,rate],index) => <div key={name} className="flex items-center gap-4"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#FFF8E6] text-sm font-semibold text-amber-700">{index+1}</div><div className="min-w-0 flex-1"><p className="font-semibold">{name}</p><p className="mt-1 text-xs text-[#6B5C3B]">{dept}</p></div><span className="font-semibold text-emerald-600">{rate}</span></div>)}</div></section></section>
  </main></OrganizerShell>
}
